
### Transform Request - XSD to CMF

@url = {{baseUrl}}/transforms/models

@from = {{format_xsd}}
@to = {{format_cmf}}
@filename = niem-core-5.0.xsd
@file = ../../../transform/{{filename}}

POST {{url}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="from"

{{from}}
--{{boundary}}
Content-Disposition: form-data; name="to"

{{to}}
--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{filename}}"
Content-Type: application/xml

< {{file}}
--{{boundary}}--
