plugins {
	id 'java'
  id "com.github.ben-manes.versions" version "0.52.0"
  id "io.freefair.lombok" version "8.14"
	id 'io.spring.dependency-management' version '1.1.7'
  id 'org.springdoc.openapi-gradle-plugin' version '1.9.0'
	id 'org.springframework.boot' version '4.0.0-M2'
  id 'checkstyle'
}

group = 'gov.niem.tools'
version = '2.0'
project.ext.draft = '2.0-alpha08:SNAPSHOT-2'

java {
  sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
	mavenCentral()
}

dependencies {
  implementation platform('org.hibernate.search:hibernate-search-platform-bom:8.1.2.Final')

  implementation fileTree(dir: 'libs/cmftool', include: '*.jar')

  implementation 'com.fasterxml.jackson.core:jackson-core'
  implementation 'com.fasterxml.jackson.core:jackson-databind'
  implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
  implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-csv'
  implementation 'com.fasterxml.jackson.dataformat:jackson-dataformats-text:2.19.0'
  implementation 'com.fasterxml.jackson.datatype:jackson-datatype-hibernate7:2.20.0-rc1'
  implementation 'com.fasterxml.jackson:jackson-bom'

  implementation 'com.github.therapi:therapi-runtime-javadoc:0.15.0'

  implementation 'commons-io:commons-io:2.20.0'

  implementation 'net.lingala.zip4j:zip4j:2.11.5'

  implementation 'net.sf.saxon:Saxon-HE:12.8'

  implementation 'org.apache.commons:commons-csv:1.14.1'

  implementation 'org.apache.lucene:lucene-backward-codecs'

  implementation 'org.hibernate.orm:hibernate-envers'

  implementation 'org.hibernate.search:hibernate-search-mapper-orm'
  implementation 'org.hibernate.search:hibernate-search-backend-lucene'

  implementation 'org.json:json:20250517'

  implementation 'org.postgresql:postgresql'

  implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.9'

  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  // implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-web'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

  annotationProcessor 'com.github.therapi:therapi-runtime-javadoc-scribe:0.15.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

compileJava {
  options.compilerArgs += ['-parameters', '-Xlint:deprecation']
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
  testImplementation {
    exclude group: 'com.vaadin.external.google', module: 'android-json'
  }
}

configurations.all {
  resolutionStrategy {
    resolutionStrategy.force 'io.smallrye:jandex:3.1.2'
    // failOnVersionConflict()
  }
}

processResources {
  filesMatching(['application.yaml', 'swagger-config.yaml']) {
    // Make application version available to the code and open-api file
    expand(project.properties)
  }
}

test {
	useJUnitPlatform()
}

// CHECKSTYLE SUPPORT *************************************

checkstyle {
  // https://checkstyle.sourceforge.io/version/9.3/
  println "Checkstyle version " + checkstyle.toolVersion
  toolVersion = "9.3"
}

checkstyleMain {
  source = 'src/main/java/gov/niem/tools/api'
}

checkstyleTest {
  source = 'src/test'
}

// JAVADOC SUPPORT ****************************************

javadoc {
  options.tags = ["todo", "example"]
  options.addStringOption('Xdoclint:missing', '-quiet')
  // options.addStringOption('Xdoclint:none', '-quiet')
}

task copyJavadocs(type: Copy) {
  group = "documentation"
  description = "Copy generated Javadoc to /docs/javadoc/"
  println "Copying generated Javadoc to /docs/javadoc/"
  from "build/docs/javadoc"
  into "/docs/javadoc"
}

javadoc.finalizedBy copyJavadocs

// OpenAPI SUPPORT ****************************************

openApi {
  apiDocsUrl.set("http://localhost:8080/api/v2/api-docs")
  customBootRun {
    args.set([
      '--spring.profiles.active=openapi'
    ])
  }
}

task copyOpenApi(type: Copy) {
  group = "documentation"
  description = "Copy the OpenAPI JSON file to /docs/"
  println "Copying the OpenAPI JSON file to /docs/"
  from "build/openapi.json"
  into "/docs/"
}

generateOpenApiDocs.finalizedBy copyOpenApi
