version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AKROTIRI
  - amazoncorretto
  - ASHMORE
  - BARTHELEMY
  - BASSAS
  - BOUVET
  - BURKINA
  - CABO
  - CAICOS
  - CJIS
  - classpath
  - CLASSTYPE
  - CLIPPERTON
  - clsa
  - cmftool
  - codequality
  - Configurer
  - CÔTE
  - CUNHA
  - cyfs
  - D’IVOIRE
  - databind
  - dataformat
  - dataformats
  - DATAPROPERTY
  - datasource
  - datatypes
  - delombok
  - Dfile
  - DHEKELIA
  - dists
  - Doclet
  - ESWATINI
  - EUSTATIUS
  - FASO
  - fasterxml
  - fips
  - fkey
  - freefair
  - FUTUNA
  - GLORIOSO
  - gradlew
  - Hamcrest
  - Hmmss
  - HOWLAND
  - ISLAS
  - jandex
  - Javadocs
  - Jaxb
  - jc3iedm
  - jdbc
  - jvmargs
  - KINGMAN
  - KITTS
  - LESTE
  - linelength
  - lingala
  - logfile
  - Lucene
  - MAARTEN
  - MARINO
  - MAYEN
  - mmucc
  - NAVASSA
  - ndex
  - NOTNIEM
  - NUMKINDS
  - OBJECTPROPERTY
  - OTHERNIEM
  - pageable
  - PARACEL
  - plpgsql
  - println
  - projectable
  - rawtypes
  - reindex
  - RICA
  - scheval
  - smallrye
  - SPRATLY
  - springdoc
  - springframework
  - stewardships
  - subprojects
  - subproperties
  - Subproperty
  - svrl
  - therapi
  - TOKELAU
  - TROMELIN
  - unaccent
  - vaadin
  - vladmihalcea
  - webmvc
  - whitespaces
  - wonka
  - Xdoclint
  - Xlint
  - xmlresolver
ignoreWords: []
import: []
