version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AKROTIRI
  - ASHMORE
  - BARTHELEMY
  - BASSAS
  - BOUVET
  - BURKINA
  - CABO
  - CAICOS
  - classpath
  - CLASSTYPE
  - CLIPPERTON
  - clsa
  - cmftool
  - CÔTE
  - CUNHA
  - D’IVOIRE
  - databind
  - dataformat
  - dataformats
  - DATAPROPERTY
  - datasource
  - datatypes
  - DHEKELIA
  - ESWATINI
  - EUSTATIUS
  - FASO
  - fasterxml
  - fkey
  - freefair
  - FUTUNA
  - GLORIOSO
  - gradlew
  - Hamcrest
  - Hmmss
  - HOWLAND
  - ISLAS
  - jandex
  - Javadocs
  - Jaxb
  - jdbc
  - KINGMAN
  - KITTS
  - LESTE
  - lingala
  - logfile
  - Lucene
  - MAARTEN
  - MARINO
  - MAYEN
  - NAVASSA
  - NUMKINDS
  - OBJECTPROPERTY
  - OTHERNIEM
  - PARACEL
  - plpgsql
  - println
  - projectable
  - rawtypes
  - reindex
  - RICA
  - smallrye
  - SPRATLY
  - springdoc
  - springframework
  - stewardships
  - subproperties
  - Subproperty
  - svrl
  - therapi
  - TOKELAU
  - TROMELIN
  - unaccent
  - webmvc
  - whitespaces
  - wonka
ignoreWords: []
import: []
