
app:
  baseUrl: https://tools.niem.gov/api/mep

spring:
  datasource:
    url: ${POSTGRES_URL_MEP}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

server:
  servlet:
    context-path: /api/mep
