
### Search properties or types

@scope = properties
# @scope = types

# Property search field examples
@niemVersionNumber = 5.2
@token = arm
@substring = arm
@prefix = nc
@type = date
@isAbstract = false
@isElement = true
@page = 10

# Type search field examples
@niemVersionNumber = 5.2
@token = arm
@substring = arm
@prefix = nc
@isElement = true
@page = 10


# Search criteria
@criteria = token=arm
@criteria = substring=person
# @criteria = substring=j:person&substring=hair
# @criteria = substring=arm
# @criteria = substring=arm&substring=service
# @criteria = substring=arm&substring=service&prefix=mo&prefix=usmtf
# @criteria = substring=arm&substring=service&prefix=em
# @criteria = substring=arm&substring=service&prefix=em&isAbstract=false
# @criteria = substring=arm&substring=service&prefix=em&isAbstract=false&type=date
# @criteria = type=VehicleType&type=VesselType
# @criteria = type=VehicleType&type=VesselType&namespaceCategory=core
# @criteria = type=VehicleType&type=VesselType&namespaceCategory=core&namespaceCategory=domain
# @criteria = type=VehicleType
# @criteria = type=PersonType
# @criteria = type=PersonType&namespaceCategory=domain
# @criteria = type=nc:PersonType&namespaceCategory=domain
# @criteria = token=person&namespaceCategory=core&namespaceCategory=domain
# @criteria = token=person&namespaceCategory=code
# @criteria = prefix=ag&prefix=lrn-dev
# @criteria = token=person&type=date
# @criteria = isElement=false


# Type search criteria
# @scope = types
# @criteria = category=complex_object&token=name
# @criteria = substring=person&substring=arm

### Search
GET {{baseUrl}}/search/{{scope}}?{{criteria}}&sortOrder=qname

### Search next page
GET {{baseUrl}}/search/{{scope}}?{{criteria}}&page=1

### Set search order
@sortOrder = name
# @sortOrder = qname
# @sortOrder = rank_name
# @sortOrder = rank_qname
# @sortOrder = score_qname
# @sortOrder = score_name
GET {{baseUrl}}/search/{{scope}}?{{criteria}}&sortOrder={{sortOrder}}

###
GET {{baseUrl}}/search/index