
### Transform Request - Filename with .pdf extension

@url = {{baseUrl}}/transforms/models

@from = {{format_cmf}}
@to = {{format_cmf}}
@filename = CrashDriver.pdf
@file = ../../../transform/{{filename}}

POST {{url}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="from"

{{from}}
--{{boundary}}
Content-Disposition: form-data; name="to"

{{to}}
--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{filename}}"
Content-Type: application/xml

< {{file}}
--{{boundary}}--
