
# CMF Validation Requests

@mediaType = json
@mediaType = csv

# Assign request variables
@url = {{baseUrl}}/validation/cmf/xml
@dir = validation/xml/cmf

@pass_filename = CrashDriver-5.0.cmf.xml
@pass_file = ../../{{dir}}/{{pass_filename}}

@fail_filename = CrashDriver-5.0-invalid.cmf.xml
@fail_file = ../../{{dir}}/{{fail_filename}}

@unsupported_version_filename = CrashDriver-0.6.cmf.xml
@unsupported_version_file = ../../transform/{{unsupported_version_filename}}

@invalid_format_filename = CrashDriver.ttl
@invalid_format_file = ../../transform/{{invalid_format_filename}}

### CMF Validation - Pass test case

POST {{url}}?mediaType={{mediaType}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{pass_filename}}"
Content-Type: application/xml

< {{pass_file}}
--{{boundary}}--


### CMF Validation - Fail test case

POST {{url}}?mediaType={{mediaType}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{fail_filename}}"
Content-Type: application/xml

< {{fail_file}}
--{{boundary}}--


### CMF Validation - Unsupported CMF version

POST {{url}}?mediaType=json
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{unsupported_version_filename}}"
Content-Type: application/xml

< {{unsupported_version_file}}
--{{boundary}}--

### CMF Validation - Test exception handling when expecting a CSV response

POST {{url}}?mediaType=csv
# Accept: text/csv, application/json
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{unsupported_version_filename}}"
Content-Type: application/xml

< {{unsupported_version_file}}
--{{boundary}}--


### CMF Validation - Invalid file format

POST {{url}}?mediaType={{mediaType}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{invalid_format_filename}}"
Content-Type: application/xml

< {{invalid_format_file}}
--{{boundary}}--
