
# Message Specification Validation Requests

@mediaType = json
# @mediaType = csv

# Assign request variables
@url = {{baseUrl}}/validation/message-specification
@dir = validation/ndr

@pass_filename = CrashDriver-6.0.zip
@pass_file = ../../{{dir}}/{{pass_filename}}

@fail_filename = Crash Driver IEPD-invalid.zip
@fail_file = ../../{{dir}}/{{fail_filename}}


### Message Specification - Pass test case

POST {{url}}?mediaType={{mediaType}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{pass_filename}}"
Content-Type: application/xml

< {{pass_file}}
--{{boundary}}--


### Message Specification - Fail test case

POST {{url}}?mediaType={{mediaType}}
Content-Type: multipart/form-data; boundary={{boundary}}

--{{boundary}}
Content-Disposition: form-data; name="file"; filename="{{fail_filename}}"
Content-Type: application/xml

< {{fail_file}}
--{{boundary}}--
